// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIlG-msBEv_fsCYOVxXyUQoCCTznI0YE0',
    appId: '1:551908410664:web:8bc38cb07a5e03c29afc1d',
    messagingSenderId: '551908410664',
    projectId: 'laundriin',
    authDomain: 'laundriin.firebaseapp.com',
    storageBucket: 'laundriin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6TKf4W8ac6wKENxwtCIlqc9N9x91FnVw',
    appId: '1:551908410664:android:ab36bfb66f35a9a99afc1d',
    messagingSenderId: '551908410664',
    projectId: 'laundriin',
    storageBucket: 'laundriin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq9j7wu0dBjqqXu3RKBBoqZt5hfh_WilU',
    appId: '1:551908410664:ios:f7171a39bd6a669f9afc1d',
    messagingSenderId: '551908410664',
    projectId: 'laundriin',
    storageBucket: 'laundriin.firebasestorage.app',
    iosBundleId: 'com.example.laundriin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIlG-msBEv_fsCYOVxXyUQoCCTznI0YE0',
    appId: '1:551908410664:web:609ee8da48ef0a119afc1d',
    messagingSenderId: '551908410664',
    projectId: 'laundriin',
    authDomain: 'laundriin.firebaseapp.com',
    storageBucket: 'laundriin.firebasestorage.app',
  );
}
